### ISSUE TITLE
Write size limits

### ISSUE THREAD

**Issue by amit-bansil** [hireformation/react-layouts#1]
e.g.

package.json:
```
"size-limit": [
    {
      "path": "dist/index.module.js",
      "name": "HexColorPicker",
      "import": "{ HexColorPicker }",
      "limit": "3 KB"
    }
  ],
```

**Comment by amit-bansil** [comment]
also .github/workflows/size.yml:
```
name: Compressed Size

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          pattern: "{**/dist/**/index.module.js,./dist/index.css}"
```
